# Generated by Django 2.0 on 2017-12-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='linkedin',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
