# Generated by Django 2.0 on 2017-12-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20171222_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Outlet'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
