# Generated by Django 2.0 on 2017-12-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20171222_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='feed_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
