# Generated by Django 2.0 on 2017-12-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20171225_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='feed_url',
        ),
    ]
