# Generated by Django 2.0 on 2017-12-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_outlet_feed_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='outlet',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
