# Generated by Django 2.0 on 2017-12-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_outlet_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='author',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.TextField(default=''),
        ),
    ]
