# Generated by Django 2.0 on 2017-12-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcrunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
